runtime: python310
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

env_variables:
  ENV: "production"
  PROJECT_NAME: "BnComplex"